### ISSUE TITLE
Won't install, tried deleting libraries but nothing

### ISSUE THREAD

**Issue by ghost** [magmamaintained/Magma-1.20.1#4] opened 2023-11-29 16:44 UTC
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.4

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://paste.ee/p/peTE1

**Steps to Reproduce:**
 1. Use the server jar
 2. Try to install it for the first time

**Description of issue:**
Crashes

**Comment by C0D3-M4513R** [comment] 2023-11-29 16:45
Duplicate of #2

**Closed as completed** 2023-11-29 17:19 UTC
